config/routes.rb
FijumaMaps::Application.routes.draw do

  resources :searches

  match 'searches' => 'searches#index', :via => :get 

  root :to => 'searches#index'

  match 'home/index' => 'home#index'
  match 'home/callback' => 'home#callback'

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :address, :latitude, :longitude, :gmaps, :name, :group_name, :time, :duration, :attendees, :event_url, :description, :city, :state, :zip_code, :venue
  acts_as_gmappable

  after_initialize :encode_description

  def gmaps4rails_address
    address
  end

  def slug
    name.downcase.gsub(" ", "_")
  end

  private

  def encode_description  
    @description = description.force_encoding "ASCII-8BIT" if description
    @name = name.force_encoding "ASCII-8BIT" if name
    @group_name = group_name.force_encoding "ASCII-8BIT" if group_name
    # @city = city.force_encoding "ASCII-8BIT"
    # @state = state.force_encoding "ASCII-8BIT"
    # @zip_code = zip_code.force_encoding "ASCII-8BIT"
  end
 
end

app/models/search.rb
class Search
  attr_reader :events, :latitude, :longitude, :api_key, :max, :date, :city, :within, :events, :title, :venue, :address, :city, :region, :postal_code, :category, :start_date, :end_date, :price, :start_time, :end_time
 
  def initialize(params)
    if params["/searches"]
      @address = params["/searches"][:search_location]
      @start_time = (Time.local(params['/searches']["start_time(1i)"], params['/searches']["start_time(2i)"], params['/searches']["start_time(3i)"]).to_i) * 1000
      @end_time = (Time.local(params['/searches']["end_time(1i)"], params['/searches']["end_time(2i)"], params['/searches']["end_time(3i)"]).to_i) * 1000
    else
      @address = '94117'
      @start_time = (DateTime.now.to_i) * 1000
      @end_time = ((DateTime.now + 24.hours).to_i) * 1000
    end
    @events = []
    meetup_search
    @events << Event.new(get_coords(@address).merge(:address => @address))
  end

  def meetup_search
    post_response = Faraday.get do |request|
      coordinates = get_coords(@address)
      request.url "https://api.meetup.com/2/open_events?key=31326e6a4a3819374d109496c6f7aa&sign=true&lon=#{coordinates[:longitude]}&lat=#{coordinates[:latitude]}&time=#{@start_time},#{@end_time}&page=20"
    end   
    meetups = JSON.parse(post_response.body)
    events = meetups['results'].each do |event|

      name = event['name']
      group_name = event['group']['name']
      time = event['time']
      duration = event['duration']
      attendees = event['yes_rsvp_count']
      event_url = event['event_url'] 
      description = event['description']
      if event['venue']
        address = event['venue']['address_1']
        city = event['venue']['city']
        state = event['venue']['state']
        zip_code = event['venue']['zip']
        latitude = event['venue']['lat']
        longitude = event['venue']['lon']
      end

      @events << Event.new(:name => name, :group_name => group_name, :time => time, :duration => duration, :attendees => attendees, :event_url => event_url, :description => description, :address => address, :city => city, :state => state, :zip_code => zip_code, :latitude => latitude, :longitude => longitude)
    end
  end

  private

  def get_coords(address)
    gcoder = Gmaps4rails::Geocoder.new(address)
    coordinates = gcoder.get_coordinates.first
    {:longitude => coordinates[:lng], :latitude => coordinates[:lat]}
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
    helper ApplicationHelper
end

app/controllers/home_controller.rb
class HomeController < ActionController::Base
  APP_ID = 'something real'
  APP_SECRET = 'something real'
  SITE_URL = 'http://localhost:3000'

  protect_from_forgery
  
   def index   
    session[:oauth] = Koala::Facebook::OAuth.new(APP_ID, APP_SECRET, SITE_URL + '/home/callback')
    @auth_url =  session[:oauth].url_for_oauth_code(:permissions=>"read_stream")  
    puts session.to_s + "<<< session"

    respond_to do |format|
       format.html {  }
     end
  end

  def callback
    if params[:code]
      # acknowledge code and get access token from FB
      session[:access_token] = session[:oauth].get_access_token(params[:code])
    end   

     # auth established, now do a graph call:

    @api = Koala::Facebook::API.new(session[:access_token])
    begin
      @graph_data = @api.get_object("/me/statuses", "fields"=>"message")
    rescue Exception=>ex
      puts ex.message
    end

  
    respond_to do |format|
     format.html {   }       
    end


  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  include ApplicationHelper


  def index
    if params['/searches']
      @location = params['/searches'][:search_location]
      @start_time = Time.local(params['/searches']["start_time(1i)"], params['/searches']["start_time(2i)"], params['/searches']["start_time(3i)"])
      @end_time = Time.local(params['/searches']["end_time(1i)"], params['/searches']["end_time(2i)"], params['/searches']["end_time(3i)"])
    end
    @events = Search.new(params).events
    @json = @events.to_gmaps4rails do |event, marker|
      if event == @events.last
        marker.infowindow render_to_string(:partial => "/searches/infowindow_address", :locals => { :event => event})
        marker.picture({:picture => "https://dl.dropboxusercontent.com/u/20963921/map_icons/soil-boring-icon.png",
                      :width => 35,
                      :height => 35})
      else
        marker.infowindow render_to_string(:partial => "/searches/infowindow", :locals => { :event => event})
        marker.title "#{event.name}"
        marker.picture({:picture => "https://dl.dropbox.com/u/20963921/map_icons/music_rock.png",
                    :width => 35,
                    :height => 35})
      end
    end
    @user_location = 
    @json.force_encoding "ASCII-8BIT"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


  def start_time
    if params["/searches"]
      @start_time
    else
      DateTime.now
    end
  end

  def end_time
    if params["/searches"]
      @end_time
    else
      DateTime.now + 24.hours
    end
  end

  def location
    if params["/searches"]
      @location
    else
      "San Francisco"
    end
  end
end

app/views/home/callback.html.erb
Looping through your statuses:<br />
<ul>

<% @graph_data.each do |status| %>
<%= status["message"] %> (<i><%=status["updated_time"]%></i>)<hr>
<% end %>
</ul>

app/views/home/index.html.erb
<%= link_to 'Authenticate this Facebook app', @auth_url, :class=>"button"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Search by FIJUMA</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"
</head>
<body>

  <% if flash[:notice] %>
    <div class="alert alert-info"><%= flash[:notice] %></div>
  <% end %>
  <% if flash[:alert] %>
    <div class="alert alert-error"><%= flash[:alert] %></div>
  <% end %>

    <%= yield %>
    <%= yield :scripts %>
</body>
</html>

app/views/searches/_infowindow.html.erb
<h4><%= event.name %><%= link_to ' (more info)', event.event_url %></h4>
<h5><%= event.address %></h5>
<h5><%= event.city %>, <%= event.state %> <%= event.zip_code %></h5> 
<h5>Description: </h5>
<h5><%= event.description.split(' ')[0..50].join(' ').html_safe %></h5>

app/views/searches/_infowindow_address.html.erb
<div id="info_address"> 
<h4>This is the address you searched for.</h4>
<h5><%= event.address %></h5>
</div>

app/views/searches/index.html.erb
<div class="floatme visible-desktop visible-tablet"><h1>FIJUMAPS.</h1></div>
<div class="floatme-mobile hidden-desktop hidden-tablet"><h3>FIJUMAPS.</h3></div>

<div id="map_canvas">
    <%= gmaps4rails(@json) %>
<div>

<head>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.js"></script>
<link href="styles.css" rel="stylesheet" type="text/css" />


<script type="text/javascript">                                         
$(document).ready(function() {

   $("tr.header").click(function () { 
      $("tr.child", $(this).parent()).slideToggle("fast");
   });


});

</script>  

</head>
<div class="infoblock hidden-phone hidden-tablet" class="accordion">
  
  <table>
  <tr class="header" id="collapse" ><td> Collapse </td></tr>

    <tr class="child"><td>
        <%= form_for searches_path, :method => "get", class: 'form-horizontal' do |f| %>
          <%= f.label(:search_location, "Location:") %>
          <%= f.text_field :search_location, :value => location  %>
          <%= f.label "Date Range:" %>
          <%= f.date_select :start_time, :default => start_time %><br>
          <%= f.date_select :end_time, :default => end_time %>
          <%= f.submit "Search", class: "btn btn-primary" %><br>
        <% end %>

    </td></tr>
  <tr class="child">
    <th>Event</th>+
    <th>Group Name</th>
    <th>Address</th>
    <th></th>
    <th></th>
  </tr>


<% @events.each do |event| %>
  <tr class="child">
    <td><%= link_to event.name[0..100], event.event_url if event.name %></td>
    <td><%= event.group_name[0..100] if event.group_name %></td>
    <td><%= event.address if event.address %></td>
  </tr>
<% end %>
</table>

</div>

<div class="infoblock-mobile visible-phone ">
        <%= form_for searches_path, :method => "get", class: 'form-horizontal' do |f| %>
          <%= f.text_field :search_location, :value => location, class: 'input-medium control-group'  %>
          <div class="hideme">
            <%= f.date_select :start_time, :default => start_time%><br>
            <%= f.date_select :end_time, :default => end_time%>
          </div>
          <%= f.submit "Search", class: "btn btn-primary" %><br>
        <% end %>
</div>

<div class="infoblock-tablet  visible-tablet">
        <%= form_for searches_path, :method => "get", class: 'form-horizontal' do |f| %>
          <%= f.text_field :search_location, :value => location, class: 'input-medium control-group'  %><br>
            <%= f.date_select :start_time, :default => start_time, class: 'input-medium control-group'%><br>
            <%= f.date_select :end_time, :default => end_time, class: 'input-medium control-group'%>
            <%= f.submit "Search", class: "btn btn-primary" %><br>
        <% end %>
</div>

<br />

<%= link_to 'New Location', root_path %>